//! Derive per-language budgets from the gold corpus: budgets stop being
//! hand-set constants and become percentile pins against admired code.
//! One-sided budgets take gold p99; bands take p05/p95; policy metrics
//! (flag params, asserts) are taste and never calibrated.

use std::error::Error;
use std::fmt::Write as _;
use std::path::PathBuf;

use crate::lang::{LANGS, Lang};
use crate::metrics::{Calib, Fmt, LangBudgets, METRICS};
use crate::report::Agg;

/// Below this many samples a percentile is noise; defaults stay.
const MIN_SAMPLES: usize = 200;

/// Where the corpus pins each budget: one-sided budgets take the gold
/// tail, bands take both flanks.
const GOLD_PIN: f64 = 0.99;
const BAND_LO: f64 = 0.05;
const BAND_HI: f64 = 0.95;

/// Scans the corpus (e.g. /tmp/gold), prints the derived table, and writes
/// calibration.toml next to the current directory. The snapshot is baked
/// in at the NEXT build — commit it.
pub fn run(roots: &[PathBuf]) -> Result<i32, Box<dyn Error>> {
    let cfg = crate::config::Config::default();
    let files = crate::collect_files(roots, &cfg);
    let mut unpoliced: Vec<String> = Vec::new();
    let mut out = String::from(
        "# Generated by `elegance calibrate` from the gold.toml corpus — do not\n\
         # hand-edit. Regenerate: ./gold-fetch.sh && elegance calibrate /tmp/gold\n\
         # then rebuild (the snapshot is compiled in).\n",
    );

    for lang in LANGS {
        let subset: Vec<PathBuf> = files
            .iter()
            .filter(|p| Lang::from_path(p) == Some(lang))
            .cloned()
            .collect();
        if subset.is_empty() {
            continue;
        }
        let mut agg = crate::scan(
            &subset,
            crate::config::Layers::flat(LangBudgets::defaults()),
            false,
        );
        let section = lang_section(&mut agg, lang);
        if !section.is_empty() {
            let _ = write!(out, "\n[{}]\n{section}", lang.name());
        }
        audit_policy(&agg, lang, &mut unpoliced);
    }

    std::fs::write("calibration.toml", &out)?;
    println!("\nwrote calibration.toml — rebuild to bake it in");
    // A policy the admired corpus fails is a wrong policy — the argument
    // this project already used to move `demeter` off Calib::Policy.
    // Reported, not gated: calibration itself succeeded, and only the
    // ratchet and diff modes may fail a build.
    if !unpoliced.is_empty() {
        println!(
            "\nPOLICY DEBT — gating budgets the gold corpus itself violates (over {:.0}%):",
            POLICY_CEILING * 100.0
        );
        for line in &unpoliced {
            println!("  {line}");
        }
        println!("  each is a detector to fix, an exemption to add, or a rung to demote.");
    }
    Ok(0)
}

/// One language's calibration entries: pinned budgets first, then the
/// coverage rates for the rate metrics, each echoed to the console.
fn lang_section(agg: &mut Agg, lang: Lang) -> String {
    let mut section = String::new();
    for (m, def) in METRICS.iter().enumerate() {
        let dist = agg.sorted_dist(m);
        if dist.len() < MIN_SAMPLES || def.calib == Calib::Policy {
            continue;
        }
        let q = |p: f64| crate::report::quantile(dist, p);
        // A zero p99 means the fact is not extracted for this language
        // (e.g. Zig live spans without def sites) — pinning hi=0 would
        // gate everything the day extraction lands.
        if def.calib == Calib::P99 && q(GOLD_PIN) == 0.0 {
            continue;
        }
        let entry = match def.calib {
            Calib::P99 => format!("hi = {:.1}", (q(GOLD_PIN) as f64).ceil()),
            Calib::Band => {
                if q(BAND_LO) == 0.0 {
                    // Truthful, and worth saying out loud: a floor of
                    // zero can never fire, so the band is one-sided by
                    // the corpus's own verdict.
                    let _ = writeln!(
                        section,
                        "# gold p05 is zero: the low flank is vacuous by the corpus's verdict"
                    );
                }
                format!("lo = {:.2}, hi = {:.2}", q(BAND_LO), q(BAND_HI))
            }
            Calib::Policy => unreachable!(),
        };
        let _ = writeln!(section, "\"{}\" = {{ {entry} }}", def.name);
        let shown = match def.fmt {
            Fmt::Int => format!("{:.0}", q(GOLD_PIN)),
            Fmt::Pct => format!("{:.0}%-{:.0}%", q(BAND_LO) * 100.0, q(BAND_HI) * 100.0),
        };
        println!(
            "{:<5} {:<15} n={:<7} gold {}",
            lang.name(),
            def.name,
            dist.len(),
            shown
        );
    }
    // Rate metrics: gold's coverage share, baked so a repo's rate
    // renders beside the admired reference.
    for m in crate::metrics::RATE_METRICS {
        let dist = agg.sorted_dist(m);
        if dist.len() < MIN_SAMPLES {
            continue;
        }
        let covered = dist.iter().filter(|v| **v > 0.0).count();
        let rate = covered as f64 / dist.len() as f64;
        let _ = writeln!(section, "\"{}\" = {{ rate = {rate:.2} }}", METRICS[m].name);
        println!(
            "{:<5} {:<15} n={:<7} gold covered {:.0}%",
            lang.name(),
            METRICS[m].name,
            dist.len(),
            rate * 100.0
        );
    }
    section
}

/// Percentiles never touch `Calib::Policy` budgets, so nothing catches a
/// policy that over-fires. Measure them anyway: a gating policy metric
/// that admired code fails is measuring taste, not quality.
const POLICY_CEILING: f64 = 0.01;

/// A suspicion may cry louder than a gate, but a rung-3/4 metric that
/// admired code fails this often is still measuring taste — the same
/// argument that turned `asserts` and `public docs` into rates.
const SUSPICION_CEILING: f64 = 0.05;

fn audit_policy(agg: &Agg, lang: Lang, unpoliced: &mut Vec<String>) {
    for (m, def) in METRICS.iter().enumerate() {
        let rate = agg.violation_rate(m);
        let ceiling = match def.rung {
            0..=2 => POLICY_CEILING,
            3..=4 => SUSPICION_CEILING,
            _ => continue,
        };
        if def.calib != Calib::Policy || rate <= ceiling {
            continue;
        }
        unpoliced.push(format!(
            "{:<5} {:<15} rung {}  gold violates {:.1}% (ceiling {:.0}%)",
            lang.name(),
            def.name,
            def.rung,
            rate * 100.0,
            ceiling * 100.0
        ));
    }
}
