//! Recall floors: seeded smells the detectors must keep finding.
//!
//! Precision has two gates — gold-corpus rates and the policy audit —
//! and recall had none: a detector that decays toward silence passes
//! every precision check by finding nothing. Each fixture under
//! `fixtures/recall/` is realistic code with COUNTED smells planted in
//! it, and this suite asserts the totals never drop.
//!
//! Scope: the count-shaped detectors (swallowed, secrets, casts, ...).
//! Distribution metrics (cognitive, length, depth) are pinned by the
//! cross-language conformance suite instead — their recall is the
//! extractor's correctness, not a detector's.
//!
//! Convention: a new detector adds a seed here AND a restraint entry in
//! the metrics RESTRAINT table — one test for firing, one for silence.
//! Fixtures end in `.seed` so no scan ever reads them as source.

use std::path::Path;

use crate::facts::extract;
use crate::lang::Lang;
use crate::metrics::{self, METRICS};

pub(crate) const FIXTURES: &[(&str, Lang, &str)] = &[
    (
        "service.py",
        Lang::Python,
        include_str!("../fixtures/recall/service.py.seed"),
    ),
    (
        "tests/test_service.py",
        Lang::Python,
        include_str!("../fixtures/recall/test_service.py.seed"),
    ),
    (
        "worker.rs",
        Lang::Rust,
        include_str!("../fixtures/recall/worker.rs.seed"),
    ),
    (
        "handler.ts",
        Lang::TypeScript,
        include_str!("../fixtures/recall/handler.ts.seed"),
    ),
    (
        "widget.js",
        Lang::JavaScript,
        include_str!("../fixtures/recall/widget.js.seed"),
    ),
    (
        "store.go",
        Lang::Go,
        include_str!("../fixtures/recall/store.go.seed"),
    ),
    (
        "store_test.go",
        Lang::Go,
        include_str!("../fixtures/recall/store_test.go.seed"),
    ),
    (
        "pool.c",
        Lang::C,
        include_str!("../fixtures/recall/pool.c.seed"),
    ),
    (
        "ring.zig",
        Lang::Zig,
        include_str!("../fixtures/recall/ring.zig.seed"),
    ),
    (
        "base.ml",
        Lang::OCaml,
        include_str!("../fixtures/recall/base.ml.seed"),
    ),
    (
        "useAccount.ts",
        Lang::TypeScript,
        include_str!("../fixtures/recall/useAccount.ts.seed"),
    ),
    (
        "deploy.sh",
        Lang::Shell,
        include_str!("../fixtures/recall/deploy.sh.seed"),
    ),
    (
        "engine.cpp",
        Lang::Cpp,
        include_str!("../fixtures/recall/engine.cpp.seed"),
    ),
    (
        "engine_test.cpp",
        Lang::Cpp,
        include_str!("../fixtures/recall/engine_test.cpp.seed"),
    ),
    (
        "handler.rb",
        Lang::Ruby,
        include_str!("../fixtures/recall/handler.rb.seed"),
    ),
    (
        "store.lua",
        Lang::Lua,
        include_str!("../fixtures/recall/store.lua.seed"),
    ),
    (
        "worker.pl",
        Lang::Perl,
        include_str!("../fixtures/recall/worker.pl.seed"),
    ),
    (
        "service.php",
        Lang::Php,
        include_str!("../fixtures/recall/service.php.seed"),
    ),
    (
        "OrderStore.java",
        Lang::Java,
        include_str!("../fixtures/recall/OrderStore.java.seed"),
    ),
    (
        "OrderStore.cs",
        Lang::CSharp,
        include_str!("../fixtures/recall/OrderStore.cs.seed"),
    ),
    (
        "OrderStore.swift",
        Lang::Swift,
        include_str!("../fixtures/recall/OrderStore.swift.seed"),
    ),
    (
        "OrderStore.scala",
        Lang::Scala,
        include_str!("../fixtures/recall/OrderStore.scala.seed"),
    ),
    (
        "order_store.ex",
        Lang::Elixir,
        include_str!("../fixtures/recall/order_store.ex.seed"),
    ),
    (
        "OrderStore.sol",
        Lang::Solidity,
        include_str!("../fixtures/recall/OrderStore.sol.seed"),
    ),
];

/// The manifest: (fixture, metric, minimum total planted). Sums may
/// legitimately GROW as detectors sharpen; they must never shrink.
/// Together with the parity matrix in lang::conformance, this doubles
/// as liveness evidence: a (metric, language) pair seeded here is
/// PROVEN alive on every test run.
pub(crate) const SEEDS: &[(&str, &str, f32)] = &[
    ("service.py", "blocking async", 2.0),
    ("service.py", "spooky", 2.0),
    ("service.py", "swallowed", 2.0),
    ("service.py", "broad catch", 1.0),
    ("service.py", "magic numbers", 2.0),
    ("service.py", "negations", 2.0),
    ("service.py", "demeter", 1.0),
    ("service.py", "secrets", 1.0),
    ("service.py", "casts", 1.0),
    ("service.py", "suppressions", 1.0),
    ("service.py", "kw opacity", 1.0),
    ("service.py", "flag params", 1.0),
    ("service.py", "loose types", 1.0),
    ("service.py", "untyped params", 3.0),
    ("service.py", "lying name", 1.0),
    ("service.py", "wildcard match", 1.0),
    ("service.py", "lost context", 1.0),
    ("tests/test_service.py", "vacuous asserts", 1.0),
    ("tests/test_service.py", "sleepy test", 1.0),
    ("tests/test_service.py", "skipped tests", 1.0),
    ("worker.rs", "skipped tests", 1.0),
    ("handler.ts", "skipped tests", 1.0),
    ("widget.js", "skipped tests", 1.0),
    ("store_test.go", "skipped tests", 1.0),
    ("worker.rs", "sleepy test", 1.0),
    ("handler.ts", "sleepy test", 1.0),
    ("widget.js", "sleepy test", 1.0),
    ("store_test.go", "sleepy test", 1.0),
    ("ring.zig", "sleepy test", 1.0),
    ("tests/test_service.py", "test asserts", 2.0),
    ("worker.rs", "blocking async", 2.0),
    ("worker.rs", "unwraps", 2.0),
    ("worker.rs", "casts", 2.0),
    ("worker.rs", "secrets", 1.0),
    ("worker.rs", "spooky", 1.0),
    ("worker.rs", "dropped tasks", 1.0),
    ("worker.rs", "wildcard match", 1.0),
    ("worker.rs", "negations", 1.0),
    ("worker.rs", "demeter", 1.0),
    ("worker.rs", "flag params", 3.0),
    ("worker.rs", "lying name", 1.0),
    ("worker.rs", "vacuous asserts", 1.0),
    ("worker.rs", "test asserts", 1.0),
    ("handler.ts", "blocking async", 1.0),
    ("handler.ts", "suppressions", 1.0),
    ("handler.ts", "casts", 2.0),
    ("handler.ts", "lost context", 1.0),
    ("handler.ts", "swallowed", 1.0),
    ("handler.ts", "loose types", 1.0),
    ("handler.ts", "wildcard match", 1.0),
    ("handler.ts", "untyped params", 1.0),
    ("handler.ts", "dropped tasks", 1.0),
    ("handler.ts", "negations", 1.0),
    ("handler.ts", "demeter", 1.0),
    ("handler.ts", "flag params", 2.0),
    ("handler.ts", "lying name", 1.0),
    ("handler.ts", "secrets", 1.0),
    ("handler.ts", "spooky", 1.0),
    ("handler.ts", "vacuous asserts", 1.0),
    ("handler.ts", "test asserts", 1.0),
    ("widget.js", "blocking async", 1.0),
    ("widget.js", "suppressions", 1.0),
    ("widget.js", "spooky", 1.0),
    ("widget.js", "swallowed", 1.0),
    ("widget.js", "lost context", 1.0),
    ("widget.js", "secrets", 1.0),
    ("widget.js", "negations", 1.0),
    ("widget.js", "demeter", 1.0),
    ("widget.js", "flag params", 1.0),
    ("widget.js", "dropped tasks", 1.0),
    ("widget.js", "wildcard match", 1.0),
    ("widget.js", "vacuous asserts", 1.0),
    ("widget.js", "test asserts", 1.0),
    ("store.go", "swallowed", 2.0),
    ("store.go", "casts", 1.0),
    ("store.go", "loose types", 1.0),
    ("store.go", "wildcard match", 1.0),
    ("store.go", "secrets", 1.0),
    ("store.go", "lying name", 1.0),
    ("store.go", "negations", 1.0),
    ("store.go", "demeter", 1.0),
    ("store.go", "flag params", 2.0),
    ("store.go", "unwraps", 1.0),
    ("store.go", "spooky", 1.0),
    ("store_test.go", "vacuous asserts", 1.0),
    ("store_test.go", "test asserts", 2.0),
    ("pool.c", "casts", 2.0),
    ("pool.c", "magic numbers", 1.0),
    ("pool.c", "secrets", 1.0),
    ("pool.c", "lying name", 1.0),
    ("pool.c", "negations", 1.0),
    ("pool.c", "unwraps", 1.0),
    ("pool.c", "spooky", 1.0),
    ("pool.c", "wildcard match", 1.0),
    ("pool.c", "flag params", 2.0),
    ("pool.c", "loose types", 1.0),
    ("ring.zig", "secrets", 1.0),
    ("ring.zig", "casts", 1.0),
    ("ring.zig", "unwraps", 1.0),
    ("ring.zig", "wildcard match", 1.0),
    ("ring.zig", "lying name", 1.0),
    ("ring.zig", "demeter", 1.0),
    ("ring.zig", "flag params", 1.0),
    ("ring.zig", "loose types", 1.0),
    ("ring.zig", "spooky", 1.0),
    ("ring.zig", "vacuous asserts", 1.0),
    ("ring.zig", "test asserts", 1.0),
    ("base.ml", "untyped params", 2.0),
    ("base.ml", "wildcard match", 1.0),
    ("base.ml", "spooky", 2.0),
    ("useAccount.ts", "conditional hook", 1.0),
    ("widget.js", "conditional hook", 1.0),
    ("deploy.sh", "secrets", 2.0),
    ("deploy.sh", "spooky", 1.0),
    ("deploy.sh", "negations", 1.0),
    ("deploy.sh", "magic numbers", 1.0),
    ("deploy.sh", "wildcard match", 1.0),
    ("service.py", "repurposed", 1.0),
    ("service.py", "unawaited coroutine", 1.0),
    ("service.py", "magic strings", 1.0),
    ("service.py", "bool traps", 1.0),
    ("service.py", "commented code", 1.0),
    ("service.py", "built query", 1.0),
    ("service.py", "shelled out", 1.0),
    // A documented parameter the signature does not declare, in the two
    // conventions that carry the check: a Google `Args:` block and a
    // JSDoc `@param`. Both fixtures document `control_codes` against a
    // parameter called `control` — rich/console.py:1610, planted.
    ("service.py", "doc param", 1.0),
    // `ceremony` was the one metric of its cohort with a restraint test
    // and no floor, which is the exact shape a detector decays into
    // silence in: the override-point exclusion that took its gold
    // findings from 195 to 3 could tighten one clause further and no
    // test would notice. A nullary free-standing declaration whose body
    // is one bare literal, documented at length and overriding nothing.
    ("service.py", "ceremony", 1.0),
    ("worker.rs", "ceremony", 1.0),
    ("handler.ts", "doc param", 1.0),
    ("handler.ts", "shelled out", 1.0),
    ("widget.js", "shelled out", 1.0),
    ("store.go", "shelled out", 1.0),
    ("handler.ts", "built query", 1.0),
    ("widget.js", "built query", 1.0),
    ("store.go", "built query", 1.0),
    ("worker.rs", "built query", 1.0),
    // Doc length is a distribution rather than a detector, so its
    // recall floor is a WORD COUNT: a field doc that runs to sixty
    // words of prose must keep measuring sixty. A pipeline change that
    // started eating sentences would pass every precision check by
    // measuring less.
    ("worker.rs", "field doc", 60.0),
    ("pool.c", "built query", 1.0),
    ("worker.rs", "bool traps", 1.0),
    ("handler.ts", "bool traps", 1.0),
    ("widget.js", "bool traps", 1.0),
    ("store.go", "bool traps", 1.0),
    ("pool.c", "bool traps", 1.0),
    ("ring.zig", "bool traps", 1.0),
    ("base.ml", "bool traps", 1.0),
    ("worker.rs", "unawaited coroutine", 1.0),
    ("worker.rs", "repurposed", 1.0),
    ("handler.ts", "repurposed", 1.0),
    ("widget.js", "repurposed", 1.0),
    ("store.go", "repurposed", 1.0),
    ("pool.c", "repurposed", 1.0),
    ("deploy.sh", "repurposed", 1.0),
    ("ring.zig", "repurposed", 1.0),
    ("engine.cpp", "secrets", 1.0),
    ("engine.cpp", "swallowed", 1.0),
    ("engine.cpp", "broad catch", 1.0),
    ("engine.cpp", "casts", 1.0),
    ("engine.cpp", "loose types", 1.0),
    ("engine.cpp", "demeter", 1.0),
    ("engine.cpp", "negations", 1.0),
    ("engine.cpp", "magic numbers", 1.0),
    ("engine.cpp", "wildcard match", 1.0),
    ("engine.cpp", "flag params", 1.0),
    ("engine.cpp", "bool traps", 1.0),
    ("engine.cpp", "repurposed", 1.0),
    ("engine.cpp", "built query", 1.0),
    ("engine.cpp", "spooky", 1.0),
    ("engine.cpp", "unwraps", 1.0),
    ("engine.cpp", "lying name", 1.0),
    ("engine_test.cpp", "test asserts", 2.0),
    ("engine_test.cpp", "vacuous asserts", 1.0),
    ("engine_test.cpp", "sleepy test", 1.0),
    ("OrderStore.cs", "secrets", 1.0),
    ("OrderStore.cs", "swallowed", 1.0),
    ("OrderStore.cs", "broad catch", 1.0),
    ("OrderStore.cs", "lost context", 1.0),
    ("OrderStore.cs", "unwraps", 1.0),
    ("OrderStore.cs", "blocking async", 1.0),
    ("OrderStore.cs", "casts", 1.0),
    ("OrderStore.cs", "spooky", 3.0),
    ("OrderStore.cs", "wildcard match", 1.0),
    ("OrderStore.cs", "negations", 1.0),
    ("OrderStore.cs", "demeter", 1.0),
    ("OrderStore.cs", "flag params", 1.0),
    ("OrderStore.cs", "loose types", 3.0),
    ("OrderStore.cs", "lying name", 1.0),
    ("OrderStore.cs", "vacuous asserts", 2.0),
    ("OrderStore.cs", "test asserts", 3.0),
    ("OrderStore.cs", "repurposed", 1.0),
    ("OrderStore.cs", "sleepy test", 1.0),
    ("OrderStore.cs", "skipped tests", 1.0),
    ("OrderStore.cs", "bool traps", 1.0),
    ("OrderStore.cs", "built query", 1.0),
    ("OrderStore.cs", "shelled out", 1.0),
    ("OrderStore.java", "secrets", 1.0),
    ("OrderStore.java", "swallowed", 1.0),
    ("OrderStore.java", "broad catch", 1.0),
    ("OrderStore.java", "lost context", 1.0),
    ("OrderStore.java", "unwraps", 1.0),
    ("OrderStore.java", "casts", 1.0),
    ("OrderStore.java", "spooky", 2.0),
    ("OrderStore.java", "wildcard match", 1.0),
    ("OrderStore.java", "negations", 1.0),
    ("OrderStore.java", "demeter", 1.0),
    ("OrderStore.java", "flag params", 1.0),
    ("OrderStore.java", "loose types", 3.0),
    ("OrderStore.java", "lying name", 1.0),
    ("OrderStore.java", "vacuous asserts", 1.0),
    ("OrderStore.java", "test asserts", 2.0),
    ("OrderStore.java", "repurposed", 1.0),
    ("OrderStore.java", "sleepy test", 1.0),
    ("OrderStore.java", "skipped tests", 1.0),
    ("OrderStore.java", "bool traps", 1.0),
    ("OrderStore.java", "built query", 1.0),
    ("OrderStore.java", "shelled out", 1.0),
    ("OrderStore.scala", "secrets", 1.0),
    ("OrderStore.scala", "swallowed", 1.0),
    ("OrderStore.scala", "broad catch", 1.0),
    ("OrderStore.scala", "lost context", 1.0),
    ("OrderStore.scala", "unwraps", 1.0),
    ("OrderStore.scala", "spooky", 1.0),
    ("OrderStore.scala", "wildcard match", 1.0),
    ("OrderStore.scala", "negations", 1.0),
    ("OrderStore.scala", "demeter", 1.0),
    ("OrderStore.scala", "flag params", 1.0),
    ("OrderStore.scala", "loose types", 1.0),
    ("OrderStore.scala", "lying name", 1.0),
    ("OrderStore.scala", "vacuous asserts", 1.0),
    ("OrderStore.scala", "test asserts", 2.0),
    ("OrderStore.scala", "repurposed", 1.0),
    ("OrderStore.scala", "sleepy test", 1.0),
    ("OrderStore.scala", "skipped tests", 1.0),
    ("OrderStore.scala", "bool traps", 1.0),
    ("OrderStore.scala", "built query", 2.0),
    ("OrderStore.scala", "shelled out", 1.0),
    ("OrderStore.sol", "secrets", 1.0),
    ("OrderStore.sol", "swallowed", 1.0),
    ("OrderStore.sol", "broad catch", 1.0),
    ("OrderStore.sol", "unwraps", 1.0),
    ("OrderStore.sol", "casts", 1.0),
    ("OrderStore.sol", "spooky", 1.0),
    ("OrderStore.sol", "negations", 1.0),
    ("OrderStore.sol", "demeter", 1.0),
    ("OrderStore.sol", "flag params", 2.0),
    ("OrderStore.sol", "loose types", 1.0),
    ("OrderStore.sol", "lying name", 1.0),
    ("OrderStore.sol", "vacuous asserts", 1.0),
    ("OrderStore.sol", "test asserts", 2.0),
    ("OrderStore.sol", "repurposed", 1.0),
    ("OrderStore.sol", "skipped tests", 1.0),
    ("OrderStore.sol", "bool traps", 1.0),
    ("OrderStore.swift", "secrets", 1.0),
    ("OrderStore.swift", "swallowed", 1.0),
    ("OrderStore.swift", "broad catch", 1.0),
    ("OrderStore.swift", "lost context", 1.0),
    ("OrderStore.swift", "unwraps", 1.0),
    ("OrderStore.swift", "blocking async", 1.0),
    ("OrderStore.swift", "casts", 1.0),
    ("OrderStore.swift", "spooky", 1.0),
    ("OrderStore.swift", "wildcard match", 1.0),
    ("OrderStore.swift", "negations", 1.0),
    ("OrderStore.swift", "demeter", 1.0),
    ("OrderStore.swift", "flag params", 1.0),
    ("OrderStore.swift", "loose types", 3.0),
    ("OrderStore.swift", "lying name", 1.0),
    ("OrderStore.swift", "vacuous asserts", 1.0),
    ("OrderStore.swift", "test asserts", 2.0),
    ("OrderStore.swift", "repurposed", 1.0),
    ("OrderStore.swift", "sleepy test", 1.0),
    ("OrderStore.swift", "skipped tests", 2.0),
    ("OrderStore.swift", "bool traps", 1.0),
    ("OrderStore.swift", "built query", 1.0),
    ("OrderStore.swift", "shelled out", 1.0),
    ("handler.rb", "secrets", 1.0),
    ("handler.rb", "swallowed", 1.0),
    ("handler.rb", "broad catch", 1.0),
    ("handler.rb", "lost context", 1.0),
    ("handler.rb", "unwraps", 1.0),
    ("handler.rb", "spooky", 1.0),
    ("handler.rb", "wildcard match", 1.0),
    ("handler.rb", "negations", 1.0),
    ("handler.rb", "demeter", 1.0),
    ("handler.rb", "kw opacity", 1.0),
    ("handler.rb", "flag params", 1.0),
    ("handler.rb", "vacuous asserts", 1.0),
    ("handler.rb", "test asserts", 2.0),
    ("handler.rb", "repurposed", 1.0),
    ("handler.rb", "sleepy test", 1.0),
    ("handler.rb", "skipped tests", 1.0),
    ("handler.rb", "bool traps", 1.0),
    ("handler.rb", "built query", 1.0),
    ("handler.rb", "shelled out", 1.0),
    ("order_store.ex", "secrets", 1.0),
    ("order_store.ex", "swallowed", 1.0),
    ("order_store.ex", "broad catch", 2.0),
    ("order_store.ex", "lost context", 1.0),
    ("order_store.ex", "spooky", 1.0),
    ("order_store.ex", "wildcard match", 1.0),
    ("order_store.ex", "negations", 1.0),
    ("order_store.ex", "flag params", 1.0),
    ("order_store.ex", "vacuous asserts", 2.0),
    ("order_store.ex", "test asserts", 2.0),
    ("order_store.ex", "sleepy test", 1.0),
    ("order_store.ex", "skipped tests", 1.0),
    ("order_store.ex", "bool traps", 1.0),
    ("order_store.ex", "built query", 1.0),
    ("order_store.ex", "shelled out", 1.0),
    ("service.php", "secrets", 1.0),
    ("service.php", "swallowed", 1.0),
    ("service.php", "broad catch", 1.0),
    ("service.php", "lost context", 1.0),
    ("service.php", "unwraps", 1.0),
    ("service.php", "casts", 1.0),
    ("service.php", "suppressions", 1.0),
    ("service.php", "spooky", 1.0),
    ("service.php", "wildcard match", 1.0),
    ("service.php", "negations", 1.0),
    ("service.php", "demeter", 1.0),
    ("service.php", "flag params", 1.0),
    ("service.php", "loose types", 4.0),
    ("service.php", "untyped params", 1.0),
    ("service.php", "lying name", 1.0),
    ("service.php", "vacuous asserts", 1.0),
    ("service.php", "test asserts", 2.0),
    ("service.php", "repurposed", 1.0),
    ("service.php", "sleepy test", 1.0),
    ("service.php", "skipped tests", 1.0),
    ("service.php", "bool traps", 1.0),
    ("service.php", "built query", 1.0),
    ("service.php", "shelled out", 1.0),
    ("store.lua", "secrets", 1.0),
    ("store.lua", "spooky", 1.0),
    ("store.lua", "negations", 1.0),
    ("store.lua", "demeter", 1.0),
    ("store.lua", "vacuous asserts", 1.0),
    ("store.lua", "test asserts", 2.0),
    ("store.lua", "repurposed", 1.0),
    ("store.lua", "sleepy test", 1.0),
    ("store.lua", "skipped tests", 1.0),
    ("store.lua", "bool traps", 1.0),
    ("store.lua", "built query", 1.0),
    ("store.lua", "shelled out", 1.0),
    ("worker.pl", "secrets", 1.0),
    ("worker.pl", "swallowed", 1.0),
    ("worker.pl", "lost context", 1.0),
    ("worker.pl", "blocking async", 1.0),
    ("worker.pl", "spooky", 1.0),
    ("worker.pl", "negations", 1.0),
    ("worker.pl", "demeter", 1.0),
    ("worker.pl", "kw opacity", 1.0),
    ("worker.pl", "flag params", 1.0),
    ("worker.pl", "vacuous asserts", 1.0),
    ("worker.pl", "test asserts", 2.0),
    ("worker.pl", "repurposed", 1.0),
    ("worker.pl", "sleepy test", 1.0),
    ("worker.pl", "skipped tests", 1.0),
    ("worker.pl", "bool traps", 1.0),
    ("worker.pl", "built query", 1.0),
    ("worker.pl", "shelled out", 1.0),
];

#[test]
fn seeded_smells_stay_found() {
    for (file, lang, src) in FIXTURES {
        let pack = lang.pack();
        let mut parser = pack.make_parser();
        let f = extract(pack, &mut parser, Path::new(file), src);
        assert!(!f.low_confidence(), "{file}: fixture must parse cleanly");
        let mut sums = vec![0f32; METRICS.len()];
        metrics::for_each(&f, |m, v, _, _| sums[m] += v);
        for (seed_file, metric, min) in SEEDS {
            if seed_file != file {
                continue;
            }
            let m = METRICS
                .iter()
                .position(|d| d.name == *metric)
                .expect("seed names a live metric");
            assert!(
                sums[m] >= *min,
                "{file}: {metric} found {} of {min} seeded — recall decayed",
                sums[m]
            );
        }
    }
    for (seed_file, ..) in SEEDS {
        assert!(
            FIXTURES.iter().any(|(f, ..)| f == seed_file),
            "seed names unknown fixture {seed_file}"
        );
    }
}
